"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState, useEffect} from "react";
export type Section="dashboard"|"campaigns"|"tasks"|"review"|"payouts"|"users"|"guide"|"admins"|"audit"|"settings";
const nav=[["/","Dashboard","▦"],["/campaigns","Campaigns","◉"],["/tasks","Tasks","✓"],["/review","Manual fallback","!"],["/payouts","Payout requests","◆"],["/users","Invited users","♙"],["/guide","AI Guide","✦"],["/admins","Admin accounts","♜"],["/audit","Audit log","≡"],["/settings","Settings","⚙"]];
const campaignRows=[["Orchard House","Product launch","Published","7","19 Jul – 12 Aug"],["Market Square","Community growth","Published","12","15 Jul – 30 Jul"],["Greenhouse Studio","Creator spotlight","Paused","6","10 Jul – 22 Jul"]];
const taskRows=[["Watch the launch reel","Orchard House","4.50 GEM","Webhook","Published"],["Visit the product story","Market Square","6.00 GEM","Pixel","Published"],["Complete feedback card","Harvest Hall","8.00 GEM","SDK event","Published"],["Local market visit","Market Square","10.00 GEM","Manual fallback","Draft"]];
function Layout({section,children}:{section:Section;children:React.ReactNode}){const path=usePathname();return <div className="admin"><aside className="aside"><div className="logo"><b>Reward Farm</b><span>Operations platform</span></div><nav className="anav">{nav.map(([href,label,ico])=><Link href={href} key={href} className={path===href?"active":""}>{ico} <span>{label}</span></Link>)}</nav><div className="adminuser"><b>Evans Simon</b><small>Super administrator</small></div></aside><main className="amain"><header className="atop"><input placeholder="Search users, tasks or campaigns…"/><div>● &nbsp; ES</div></header><div className="acontent">{children}</div></main></div>}
function Head({title,desc,action}:{title:string;desc:string;action?:string}){return <div className="ahead"><div><h1>{title}</h1><p>{desc}</p></div>{action&&<button className="abtn">{action}</button>}</div>}
function Dashboard(){return <><Head title="Operations overview" desc="Sunday, 19 July · Only real action queues are surfaced here"/><div className="metrics">{[["Invited users","128","+7 this month"],["Active tasks","24","18 auto-detected"],["Open payout requests","6","Oldest: 2 days"],["Manual fallback","3","Needs a human look"]].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></div>)}</div><div className="agrid"><section className="abox"><h2>Current campaign activity</h2><Table headers={["Campaign","State","Completions","Open tasks"]} rows={[["Orchard House","Published","384","5"],["Market Square","Published","271","8"],["Greenhouse Studio","Paused","96","3"]]}/></section><aside className="abox"><h2>Needs attention</h2><div className="queue"><div className="qitem"><b>3 manual fallback completions</b><p>Tasks without an available automatic signal.</p><Link href="/review" className="status amber">Open queue</Link></div><div className="qitem"><b>6 payout notifications</b><p>Manual arrangements happen outside the app.</p><Link href="/payouts" className="status">View oldest first</Link></div><div className="qitem"><b>2 flagged Guide messages</b><p>Read-only moderation queue.</p><Link href="/guide" className="status red">Review</Link></div></div></aside></div></>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="tablewrap"><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===1&&["Published","Active","Paid"].includes(c)?<span className="status">{c}</span>:j===1&&["Paused","Requested"].includes(c)?<span className="status amber">{c}</span>:c}</td>)}</tr>)}</tbody></table></div>}
function Campaigns(){
  const [rows, setRows] = useState<string[][] | null>(null);
  useEffect(() => {
    let mounted = true;
    fetch('/api/campaigns')
      .then((r) => r.json())
      .then((data) => {
        if (!mounted) return;
        const mapped = (data || []).map((c: any) => [
          c.title || 'Untitled',
          (c.description || '').slice(0, 40),
          c.status || 'draft',
          c._tasks_count ? String(c._tasks_count) : '-',
          (c.starts_at ? new Date(c.starts_at).toLocaleDateString() : '') + (c.ends_at ? ` – ${new Date(c.ends_at).toLocaleDateString()}` : '')
        ]);
        setRows(mapped);
      })
      .catch(() => setRows([]));
    return () => { mounted = false; };
  }, []);
  return <>
    <Head title="Campaigns" desc="Create the campaign houses that appear in Campaign City." action="New campaign"/>
    <section className="abox">
      {rows === null ? <div>Loading campaigns…</div> : <Table headers={["Campaign","Type","State","Tasks","Schedule"]} rows={rows}/>} 
    </section>
  </>;
}
function Tasks(){return <><Head title="Tasks" desc="Automatic completion detection is the default. Manual is only a rare fallback." action="Create task"/><div className="notice"><b>No proof-upload system.</b> Webhook, SDK-event and pixel signals confirm supported tasks. Manual tasks may contain one optional note or link—never a screenshot/evidence pipeline.</div><section className="abox"><Table headers={["Task","Campaign","Reward","Completion","State"]} rows={taskRows}/></section></>}
function Review(){const [items,setItems]=useState(["Local market visit · Ada Okafor","Venue attendance · Chidi Nwosu","Offline product check · Sarah Bello"]);return <><Head title="Manual fallback" desc="Only exceptional tasks with no available automatic signal appear here."/><div className="notice">There is no evidence gallery or proof workflow. Review the optional note/link and confirm the known participant’s completion.</div><section className="abox"><div className="queue">{items.map(x=><div className="qitem" key={x}><b>{x}</b><p>Optional note: Completed during Saturday’s field session with the team.</p><div className="qactions"><button onClick={()=>setItems(items.filter(i=>i!==x))}>Approve</button><button onClick={()=>setItems(items.filter(i=>i!==x))}>Reject with reason</button></div></div>)}</div></section></>}
function Payouts(){return <><Head title="Payout requests" desc="Notifications for the owner’s manual, off-platform arrangements."/><div className="notice">Marking a request paid records a status only. Reward Farm never sends money, validates a wallet, or converts GEM.</div><section className="abox"><Table headers={["User","State","Tally","Reference","Requested"]} rows={[["Ada Okafor","Requested","1,840.00 GEM","USDT TRC20","17 Jul"],["Chidi Nwosu","Requested","920.50 GEM","Bank transfer","18 Jul"],["Sarah Bello","Paid","2,105.00 GEM","Cash","15 Jul"]]}/></section></>}
function Users(){return <><Head title="Invited users" desc="Known participants only. There is no open public registration." action="Invite user"/><section className="abox"><Table headers={["Participant","Status","Current tally","Tasks","Last active"]} rows={[["Ada Okafor","Active","1,840.00 GEM","63","Today"],["Chidi Nwosu","Active","920.50 GEM","31","Today"],["Sarah Bello","Active","2,105.00 GEM","74","Yesterday"],["David Eze","Suspended","318.00 GEM","12","8 Jul"]]}/></section></>}
function Guide(){return <><Head title="AI Guide moderation" desc="Read-only farm guidance and Campaign Finder conversations."/><div className="metrics"><div className="metric"><small>Guide enabled users</small><b>84</b><em>Platform switch: on</em></div><div className="metric"><small>Messages today</small><b>146</b><em>Within daily cap</em></div><div className="metric"><small>Flagged messages</small><b>2</b><em>Needs review</em></div><div className="metric"><small>Suggested campaigns</small><b>38</b><em>All deep-linked</em></div></div><section className="abox" style={{marginTop:15}}><Table headers={["User","Conversation","Grounded calls","State"]} rows={[["Ada Okafor","What needs care today?","tasks, tally","Clean"],["Chidi Nwosu","Which campaign suits me?","campaigns, tasks","Flagged"],["Sarah Bello","Explain flowering state","submissions","Clean"]]}/></section></>}
function Admins(){return <><Head title="Admin accounts" desc="Roles, invitations, session revocation and account state." action="Invite administrator"/><section className="abox"><Table headers={["Administrator","Role","Status","Last login"]} rows={[["Evans Simon","Super admin","Active","Now"],["Lovelyn A.","Admin","Active","Today"],["Operations Desk","Admin","Active","Yesterday"]]}/></section></>}
function Audit(){return <><Head title="Audit log" desc="Immutable record of administrative changes."/><section className="abox"><Table headers={["Time","Actor","Action","Target","Result"]} rows={[["17:42","Evans Simon","Published campaign","Orchard House","Success"],["16:11","Lovelyn A.","Marked payout paid","Sarah Bello","Success"],["14:05","Operations Desk","Created task version","Launch reel v3","Success"]]}/></section></>}
function Settings(){return <><Head title="Platform settings" desc="Shared controls for both Reward Farm applications."/><div className="agrid"><section className="abox"><h2>Completion defaults</h2><div className="formgrid"><div className="field"><label>Default method</label><select><option>Webhook</option><option>SDK event</option><option>Pixel</option></select></div><div className="field"><label>Signal timeout</label><input defaultValue="3600 seconds"/></div><div className="field"><label>Daily task cap</label><input defaultValue="12"/></div><div className="field"><label>Guide message cap</label><input defaultValue="40 / day"/></div></div></section><aside className="abox"><h2>Platform rules</h2><p>No FX conversion</p><p>No payment processing</p><p>Invite-only access</p><p>AI Guide read-only</p><button className="abtn">Save settings</button></aside></div></>}
export function AdminApp({section}:{section:Section}){let body:React.ReactNode;switch(section){case"campaigns":body=<Campaigns/>;break;case"tasks":body=<Tasks/>;break;case"review":body=<Review/>;break;case"payouts":body=<Payouts/>;break;case"users":body=<Users/>;break;case"guide":body=<Guide/>;break;case"admins":body=<Admins/>;break;case"audit":body=<Audit/>;break;case"settings":body=<Settings/>;break;default:body=<Dashboard/>}return <Layout section={section}>{body}</Layout>}
