"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useCallback,useEffect,useState} from "react";
import {authHeaders,supabaseBrowser} from "@/lib/supabase-browser";
export type Section="dashboard"|"campaigns"|"tasks"|"review"|"payouts"|"users"|"guide"|"admins"|"audit"|"settings";
// Supabase rows are dynamically shaped by each selected resource.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
const nav=[["/","Dashboard","▦"],["/campaigns","Campaigns","◉"],["/tasks","Tasks","✓"],["/review","Manual fallback","!"],["/payouts","Payout requests","◆"],["/users","Invited users","♙"],["/guide","AI Guide","✦"],["/admins","Admin accounts","♜"],["/audit","Audit log","≡"],["/settings","Settings","⚙"]];
async function api(resource:string,init:RequestInit={}){
 const headers={...(await authHeaders()),"Content-Type":"application/json",...(init.headers||{})};
 const r=await fetch(`/api/admin/${resource}`,{...init,headers});
 if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||`Request failed (${r.status})`);}
 return r.status===204?null:r.json();
}
function useResource(resource:string){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setRows(await api(resource));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false)}},[resource]);
 // Resource changes intentionally initiate an asynchronous refresh.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]); return {rows,loading,error,load};
}
function Layout({children,identity,onLogout}:{children:React.ReactNode;identity:string;onLogout:()=>void}){const path=usePathname();return <div className="admin"><aside className="aside"><div className="logo"><b>Reward Farm</b><span>Operations platform</span></div><nav className="anav">{nav.map(([href,label,ico])=><Link href={href} key={href} className={path===href?"active":""}>{ico} <span>{label}</span></Link>)}</nav><button className="adminuser" onClick={onLogout}><b>{identity}</b><small>Administrator · Sign out</small></button></aside><main className="amain"><header className="atop"><input placeholder="Search users, tasks or campaigns…"/><div>● &nbsp; {identity.slice(0,2).toUpperCase()}</div></header><div className="acontent">{children}</div></main></div>}
function Head({title,desc,action,onAction}:{title:string;desc:string;action?:string;onAction?:()=>void}){return <div className="ahead"><div><h1>{title}</h1><p>{desc}</p></div>{action&&<button className="abtn" onClick={onAction}>{action}</button>}</div>}
function State({loading,error,empty=false}:{loading:boolean;error:string;empty?:boolean}){if(loading)return <div className="notice">Loading…</div>;if(error)return <div className="notice">{error}</div>;if(empty)return <div className="notice">No records found.</div>;return null}
function Actions({row,resource,reload}:{row:Row;resource:string;reload:()=>void}){
 async function state(status:string){try{await api(resource,{method:"PATCH",body:JSON.stringify({id:row.id,status})});await reload()}catch(e){alert(e)}}
 async function edit(){const title=prompt("Title",row.title||row.display_name||"");if(title===null)return;const field=resource==="users"?"display_name":"title";try{await api(resource,{method:"PATCH",body:JSON.stringify({id:row.id,[field]:title})});await reload()}catch(e){alert(e)}}
 async function remove(){if(!confirm("Delete this record permanently?"))return;try{await api(`${resource}?id=${row.id}`,{method:"DELETE"});await reload()}catch(e){alert(e)}}
 return <div className="qactions"><button onClick={edit}>Edit</button>{["campaigns","tasks"].includes(resource)&&<><button onClick={()=>state("published")}>Publish</button><button onClick={()=>state("paused")}>Pause</button><button onClick={()=>state("archived")}>Archive</button><button onClick={remove}>Delete</button></>}</div>
}
function Login({onReady}:{onReady:()=>void}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setError("");const s=supabaseBrowser();if(!s){setError("Supabase public environment variables are missing.");return}const {error}=await s.auth.signInWithPassword({email,password});if(error)setError(error.message);else onReady()}
 return <div className="admin"><main className="amain"><div className="acontent"><Head title="Administrator sign in" desc="Use an authorized Reward Farm administrator account."/><section className="abox"><form className="formgrid" onSubmit={submit}><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></div><div className="field"><label>Password</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></div>{error&&<div className="notice">{error}</div>}<button className="abtn" type="submit">Sign in</button></form></section></div></main></div>
}
function Dashboard(){const {rows:raw,loading,error}=useResource("dashboard");// Dashboard has an aggregate response rather than a row array.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const d=raw as any;const m=d.metrics||{};return <><Head title="Operations overview" desc="Live operational queues and campaign activity."/><State loading={loading} error={error}/>{!loading&&!error&&<><div className="metrics">{[["Invited users",m.users||0],["Active tasks",m.tasks||0],["Open payout requests",m.payouts||0],["Manual fallback",m.reviews||0]].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><em>Live from Supabase</em></div>)}</div><section className="abox" style={{marginTop:15}}><h2>Current campaign activity</h2><Table headers={["Campaign","State","Tasks"]} rows={(d.campaigns||[]).map((x:Row)=>[x.title,x.status,String(x.tasks?.[0]?.count||0)])}/></section></>}</>}
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="tablewrap"><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Campaigns(){const r=useResource("campaigns");async function create(){const title=prompt("Campaign title");if(!title)return;const description=prompt("Description")||"";try{await api("campaigns",{method:"POST",body:JSON.stringify({title,description,status:"draft"})});await r.load()}catch(e){alert(e)}}return <><Head title="Campaigns" desc="Create the campaign houses that appear in Campaign City." action="New campaign" onAction={create}/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["Campaign","Type","State","Tasks","Schedule","Actions"]} rows={r.rows.map(x=>[x.title,x.description||"—",x.status,String(x.tasks?.[0]?.count||0),[x.starts_at,x.ends_at].filter(Boolean).map(v=>new Date(v).toLocaleDateString()).join(" – ")||"—",<Actions key={x.id} row={x} resource="campaigns" reload={r.load}/>])}/>}</section></>}
function Tasks(){const r=useResource("tasks");async function create(){const title=prompt("Task title");if(!title)return;const campaign_id=prompt("Campaign ID");if(!campaign_id)return;const reward=Number(prompt("Reward in GEM","1")||0);const method=prompt("Completion method: webhook, sdk_event, pixel, manual, or youtube","youtube")||"youtube";const verification_config=method==="youtube"?{video_url:prompt("YouTube video URL")||"",action:prompt("YouTube action: watch, like, comment, subscribe","watch")||"watch"}:{};try{await api("tasks",{method:"POST",body:JSON.stringify({title,campaign_id,instructions:prompt("Instructions")||title,reward_cents:Math.round(reward*100),status:"draft",verification_method:method,verification_config})});await r.load()}catch(e){alert(e)}}return <><Head title="Tasks" desc="Configure automatic, YouTube, or manual completion tasks." action="Create task" onAction={create}/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["Task","Campaign","Reward","Completion","State","Actions"]} rows={r.rows.map(x=>[x.title,x.campaigns?.title||"—",`${(x.reward_cents/100).toFixed(2)} GEM`,x.verification_method,x.status,<Actions key={x.id} row={x} resource="tasks" reload={r.load}/>])}/>}</section></>}
function Review(){const r=useResource("submissions");async function decide(id:string,decision:string){const reason=decision==="rejected"?prompt("Rejection reason")||"":"";try{await api("submissions",{method:"POST",body:JSON.stringify({action:"review",id,decision,reason})});await r.load()}catch(e){alert(e)}}const rows=r.rows.filter(x=>x.status==="pending"&&x.verification_path==="manual");return <><Head title="Manual fallback" desc="Exceptional completions awaiting an administrator decision."/><section className="abox"><State loading={r.loading} error={r.error} empty={!rows.length}/><div className="queue">{rows.map(x=><div className="qitem" key={x.id}><b>{x.tasks?.title||"Task"} · {x.profiles?.display_name||x.user_id}</b><p>{x.submission_notes?.note||"No note"} {x.submission_notes?.reference_link||""}</p><div className="qactions"><button onClick={()=>decide(x.id,"approved")}>Approve</button><button onClick={()=>decide(x.id,"rejected")}>Reject with reason</button></div></div>)}</div></section></>}
function Payouts(){const r=useResource("payouts");async function mark(x:Row,status:string){const note=prompt("Administrator note",x.admin_note||"")||"";try{await api("payouts",{method:"PATCH",body:JSON.stringify({id:x.id,status,admin_note:note,resolved_at:new Date().toISOString()})});await r.load()}catch(e){alert(e)}}return <><Head title="Payout requests" desc="Review requests and record processing details."/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["User","State","Tally","Reference","Requested","Actions"]} rows={r.rows.map(x=>[x.profiles?.display_name||x.user_id,x.status,`${((x.requested_amount_cents||0)/100).toFixed(2)} GEM`,x.wallet_addresses?.label||x.wallet_addresses?.network||"—",new Date(x.created_at).toLocaleDateString(),<div className="qactions" key={x.id}><button onClick={()=>mark(x,"paid")}>Mark paid</button><button onClick={()=>mark(x,"dismissed")}>Dismiss</button></div>])}/>}</section></>}
function Users(){const r=useResource("users");async function invite(){const email=prompt("User email");if(!email)return;const display_name=prompt("Display name")||email;try{await api("users",{method:"POST",body:JSON.stringify({email,display_name})});await r.load()}catch(e){alert(e)}}async function status(x:Row,status:string){try{await api("users",{method:"PATCH",body:JSON.stringify({id:x.id,status})});await r.load()}catch(e){alert(e)}}return <><Head title="Invited users" desc="Known participants and account status." action="Invite user" onAction={invite}/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["Participant","Status","Language","Created","Actions"]} rows={r.rows.map(x=>[x.display_name||x.id,x.status,x.preferred_language,new Date(x.created_at).toLocaleDateString(),<div className="qactions" key={x.id}><button onClick={()=>status(x,x.status==="suspended"?"active":"suspended")}>{x.status==="suspended"?"Restore":"Suspend"}</button><Actions row={x} resource="users" reload={r.load}/></div>])}/>}</section></>}
function Guide(){const r=useResource("youtube");async function connect(){try{const h=await authHeaders();const res=await fetch("/api/youtube/connect",{headers:h});const data=await res.json();if(!res.ok)throw new Error(data.error);location.href=data.url}catch(e){alert(e)}}return <><Head title="YouTube integrations" desc="Connected YouTube channels used by Reward Farm tasks." action="Connect YouTube" onAction={connect}/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["Channel","Account","State","Updated"]} rows={r.rows.map(x=>[x.channel_title||x.channel_id,x.google_account_email||"—",x.status,new Date(x.updated_at).toLocaleString()])}/>}</section></>}
function Admins(){const r=useResource("admins");async function invite(){const email=prompt("Administrator email");if(!email)return;const role=prompt("Role: admin or super_admin","admin")||"admin";try{await api("admins",{method:"POST",body:JSON.stringify({email,role})});await r.load()}catch(e){alert(e)}}return <><Head title="Admin accounts" desc="Roles, invitations, session revocation and account state." action="Invite administrator" onAction={invite}/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["Administrator","Role","Status","Last login"]} rows={r.rows.map(x=>[x.user_id,x.role,x.disabled_at?"Disabled":"Active",x.last_login_at?new Date(x.last_login_at).toLocaleString():"—"])}/>}</section></>}
function Audit(){const r=useResource("audit");return <><Head title="Audit log" desc="Immutable record of administrative changes."/><section className="abox"><State loading={r.loading} error={r.error} empty={!r.rows.length}/>{!!r.rows.length&&<Table headers={["Time","Actor","Action","Target","Details"]} rows={r.rows.map(x=>[new Date(x.created_at).toLocaleString(),x.actor_id||"System",x.action,x.target_type,JSON.stringify(x.details)])}/>}</section></>}
function Settings(){const r=useResource("settings");async function save(){const cap=Number(prompt("Daily task cap",String(r.rows.find(x=>x.key==="daily_task_cap")?.value||12)));try{const existing=r.rows.find(x=>x.key==="daily_task_cap");if(existing)await api("settings",{method:"PATCH",body:JSON.stringify({id:existing.key,value:cap})});else await api("settings",{method:"POST",body:JSON.stringify({key:"daily_task_cap",value:cap})});await r.load()}catch(e){alert(e)}}return <><Head title="Platform settings" desc="Shared controls for both Reward Farm applications." action="Save settings" onAction={save}/><section className="abox"><State loading={r.loading} error={r.error}/><Table headers={["Setting","Value","Updated"]} rows={r.rows.map(x=>[x.key,JSON.stringify(x.value),new Date(x.updated_at).toLocaleString()])}/></section></>}
export function AdminApp({section}:{section:Section}){const [ready,setReady]=useState(false),[identity,setIdentity]=useState("");useEffect(()=>{const s=supabaseBrowser();s?.auth.getSession().then(({data})=>{setReady(!!data.session);setIdentity(data.session?.user.email||"Admin")});const {data:l}=s?.auth.onAuthStateChange((_e,v)=>{setReady(!!v);setIdentity(v?.user.email||"Admin")})||{data:null};return()=>l?.subscription.unsubscribe()},[]);if(!ready)return <Login onReady={()=>setReady(true)}/>;let body:React.ReactNode;switch(section){case"campaigns":body=<Campaigns/>;break;case"tasks":body=<Tasks/>;break;case"review":body=<Review/>;break;case"payouts":body=<Payouts/>;break;case"users":body=<Users/>;break;case"guide":body=<Guide/>;break;case"admins":body=<Admins/>;break;case"audit":body=<Audit/>;break;case"settings":body=<Settings/>;break;default:body=<Dashboard/>}return <Layout identity={identity} onLogout={()=>supabaseBrowser()?.auth.signOut()}>{body}</Layout>}
