"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useMemo, useState } from "react";

export type FarmView = "farm"|"work"|"city"|"vault"|"guide"|"profile"|"notifications"|"campaign"|"task"|"not-found";
type Task = {id:string; icon:string; title:string; campaign:string; reward:string; status:string; detail:string; progress:number};

const tasks: Task[] = [
  {id:"orchard-reel",icon:"▶",title:"Watch the launch reel",campaign:"Orchard House",reward:"4.50 GEM",status:"Ready",detail:"Watch the full campaign reel. Completion is noticed automatically.",progress:0},
  {id:"market-story",icon:"✦",title:"Visit the product story",campaign:"Market Square",reward:"6 GEM",status:"Growing",detail:"Your visit was recorded. The plot is growing while the campaign confirms it.",progress:68},
  {id:"harvest-survey",icon:"✓",title:"Complete the feedback card",campaign:"Harvest Hall",reward:"8 GEM",status:"Ready to harvest",detail:"The campaign confirmed your completion. Collect the harvest when ready.",progress:100},
  {id:"greenhouse",icon:"♬",title:"Listen to the creator spotlight",campaign:"Greenhouse Studio",reward:"3.25 GEM",status:"Needs water",detail:"Open the spotlight and listen through the final segment.",progress:18},
];
const campaigns = [
  {id:"orchard-house",icon:"🏛️",name:"Orchard House",type:"Product launch",tasks:7,open:5,accent:"#53e39d"},
  {id:"market-square",icon:"🏙️",name:"Market Square",type:"Community growth",tasks:12,open:8,accent:"#f5c85b"},
  {id:"greenhouse-studio",icon:"🎙️",name:"Greenhouse Studio",type:"Creator campaign",tasks:6,open:3,accent:"#75b9ff"},
];

const nav = [["/","Farm","⌂"],["/work","Work","✓"],["/city","Campaign City","▦"],["/vault","Farm Vault","◆"],["/guide","Guide","✦"]];

function Shell({view,children}:{view:FarmView;children:React.ReactNode}){
 const path=usePathname();
 return <div className="app"><div className="shell"><aside className="side"><div className="brand"><div className="brandmark">RF</div><div><strong>Reward Farm</strong><span>Campaign world</span></div></div><nav className="nav">{nav.map(([href,label,ico])=><Link key={href} href={href} className={(path===href||(href!=="/"&&path.startsWith(href)))?"active":""}><span className="ico">{ico}</span>{label}</Link>)}</nav><div className="sidefoot"><small>Farm level 7</small><b>Meadow Estate</b><div className="progress"><i style={{width:"72%"}}/></div><small>280 activity points to next plot</small></div></aside><main className="main"><header className="top"><div><h1>{view==="farm"?"Good evening, Evans":view==="city"?"Campaign City":view==="vault"?"Farm Vault":view==="work"?"Today’s farm work":"Reward Farm"}</h1><p>Sunday, 19 July · Clear skies over Meadow Estate</p></div><div className="top-actions"><Link className="pill" href="/vault"><span>Harvest tally&nbsp;</span><b>1,250.00 GEM</b></Link><Link className="iconbtn" href="/notifications">●</Link><Link className="iconbtn" href="/profile">ES</Link></div></header><div className="content">{children}</div></main></div><nav className="mobile-nav">{nav.map(([href,label,ico])=><Link key={href} href={href} className={(path===href||(href!=="/"&&path.startsWith(href)))?"active":""}><span>{ico}</span>{label}</Link>)}</nav></div>
}

function FarmHome(){return <><div className="hero"><section className="world"><div className="sky"/><div className="worldhud"><div className="eyebrow">Farm World · Close view</div><h2>Meadow Estate</h2><p>Your farm shows what is happening now. Tap any district for exact task and harvest details.</p></div><div className="road r1"/><div className="road r2"/><Link href="/work" className="district d1"><div className="dicon">🌱</div><h3>Task Fields</h3><p>4 plots need attention</p><span className="state">2 ready today</span></Link><Link href="/city" className="district d2"><div className="dicon">🏙️</div><h3>Campaign Road</h3><p>Travel to Campaign City</p><span className="state">3 active houses</span></Link><Link href="/vault" className="district d3"><div className="dicon">🏦</div><h3>Farm Vault</h3><p>Harvests and requests</p><span className="state">1,250 GEM</span></Link><Link href="/guide" className="district d4"><div className="dicon">🧭</div><h3>Guide Lodge</h3><p>Ask what needs care</p><span className="state">Guide available</span></Link></section><aside className="panel guide"><div className="guidehead"><div className="avatar">🌾</div><div><strong>Farm Guide</strong><p>Grounded in your current farm</p></div></div><div className="guidecard">Two plots need care today. The Harvest Hall feedback card is ready to collect, and the Greenhouse spotlight has not finished growing.</div><div className="attention"><h3>Today’s farm care</h3><div className="care"><Link href="/task/harvest-survey"><span>Harvest Hall</span><em>Collect 8 GEM →</em></Link><Link href="/task/greenhouse"><span>Greenhouse Studio</span><em>Continue →</em></Link><Link href="/city"><span>Campaign City</span><em>3 new tasks →</em></Link></div></div><div className="chat"><input aria-label="Ask the farm guide" placeholder="Ask about your farm…"/><button className="btn">Ask</button></div></aside></div><div className="sectionhead"><div><h2>Growing across your farm</h2><p>Every plot reflects a real task state.</p></div><Link href="/work">See all work →</Link></div><div className="cards">{tasks.slice(0,3).map(t=><TaskCard key={t.id} task={t}/>)}</div></>}

function TaskCard({task}:{task:Task}){return <Link className="card" href={`/task/${task.id}`}><div className="cardtop"><span className="tag">{task.status}</span><span className="reward">+{task.reward}</span></div><h3>{task.icon} &nbsp;{task.title}</h3><p>{task.campaign} · {task.detail}</p><div className="progress"><i style={{width:`${task.progress}%`}}/></div><div className="meta"><span>{task.progress}% grown</span><span>Open plot →</span></div></Link>}

function Work(){const [filter,setFilter]=useState("All");return <><div className="pagehead"><div><div className="eyebrow">Structured work view</div><h2>Today’s farm work</h2><p>Exact task status, reward and timing—full parity with the visual farm.</p></div><button className="btn secondary">Accessibility settings</button></div><div className="toolbar"><input className="search" placeholder="Search tasks or campaigns"/>{["All","Ready","Growing","Harvest"].map(x=><button onClick={()=>setFilter(x)} className="filter" key={x} style={filter===x?{borderColor:"#53e39d",color:"#53e39d"}:{}}>{x}</button>)}</div><div className="grid2"><div className="list">{tasks.filter(t=>filter==="All"||t.status.toLowerCase().includes(filter.toLowerCase())).map(t=><Link className="row" href={`/task/${t.id}`} key={t.id}><div className="rowicon">{t.icon}</div><div className="rowmain"><h3>{t.title}</h3><p>{t.campaign} · {t.status} · {t.detail}</p><div className="progress"><i style={{width:`${t.progress}%`}}/></div></div><div className="rowright"><b>+{t.reward}</b><small>View details →</small></div></Link>)}</div><aside className="panel"><div className="eyebrow">Work summary</div><h2>4 active plots</h2><p className="muted">One harvest is ready now. Two tasks are still growing and one has not started.</p><div className="care"><a><span>Ready to harvest</span><em>1</em></a><a><span>Growing</span><em>2</em></a><a><span>Needs water</span><em>1</em></a></div></aside></div></>}

function City(){return <><div className="pagehead"><div><div className="eyebrow">World map · East road</div><h2>Campaign City</h2><p>Explore active campaigns as places. Every open door leads to real available work.</p></div><Link href="/" className="btn secondary">Return to farm</Link></div><div className="world" style={{minHeight:430,background:"linear-gradient(180deg,#1a3540 0 34%,#32463b 34%)"}}><div className="sky"/><div className="worldhud"><h2>City District</h2><p>Three campaign houses are open today.</p></div>{campaigns.map((c,i)=><Link key={c.id} href={`/campaign/${c.id}`} className={`district d${i+1}`} style={{borderColor:c.accent}}><div className="dicon">{c.icon}</div><h3>{c.name}</h3><p>{c.type}</p><span className="state">{c.open} tasks open</span></Link>)}</div><div className="sectionhead"><div><h2>Open campaign houses</h2><p>Published by the farm team.</p></div></div><div className="cards">{campaigns.map(c=><Link className="card" href={`/campaign/${c.id}`} key={c.id}><div className="cardtop"><span className="tag">Open</span><span>{c.icon}</span></div><h3>{c.name}</h3><p>{c.type} · {c.open} of {c.tasks} tasks currently available.</p><button className="btn">Enter campaign</button></Link>)}</div></>}

function Vault(){const [requested,setRequested]=useState(false);return <><div className="pagehead"><div><div className="eyebrow">Farm Vault</div><h2>Your harvest tally</h2><p>GEM COIN is an internal activity tally. The app does not assign it a cash value.</p></div><button onClick={()=>setRequested(true)} className="btn gold">Request payout</button></div>{requested&&<div className="panel" style={{marginBottom:16,borderColor:"#53e39d"}}><b>Request sent to the farm owner</b><p className="muted">This is a notification only. Any payment arrangement happens outside Reward Farm.</p></div>}<div className="statgrid"><div className="stat"><small>Current tally</small><b>1,250.00 GEM</b></div><div className="stat"><small>This month</small><b>+184.50 GEM</b></div><div className="stat"><small>Ready requests</small><b>1</b></div><div className="stat"><small>Completed tasks</small><b>47</b></div></div><div className="grid2"><section className="panel"><h2>Harvest history</h2><div className="list">{[["Feedback card","Harvest Hall","+8.00 GEM"],["Launch reel","Orchard House","+4.50 GEM"],["Community visit","Market Square","+6.00 GEM"]].map(x=><div className="row" key={x[0]}><div className="rowicon">✦</div><div className="rowmain"><h3>{x[0]}</h3><p>{x[1]} · Automatically confirmed</p></div><div className="rowright"><b>{x[2]}</b><small>Added to tally</small></div></div>)}</div></section><aside className="panel"><h2>Payout reference</h2><p className="muted">Plain reference details for the owner. Reward Farm never sends or validates payments.</p><label className="eyebrow">Method / network</label><input className="search" defaultValue="USDT TRC20"/><br/><br/><label className="eyebrow">Reference details</label><input className="search" defaultValue="TQ8…4rWp"/><br/><br/><button className="btn secondary">Save reference</button></aside></div></>}

function Guide(){const [messages,setMessages]=useState(["Your Harvest Hall plot is ready. Collecting it will add 8 GEM to your tally. The Greenhouse spotlight still needs attention."]);const [text,setText]=useState("");return <div className="grid2"><section className="panel"><div className="guidehead"><div className="avatar">🌾</div><div><h2 style={{margin:0}}>Farm & City Guide</h2><p>Read-only guidance from your live farm state</p></div></div><div className="list" style={{marginTop:22}}>{messages.map((m,i)=><div className="guidecard" key={i}>{m}</div>)}</div><div className="chat" style={{marginTop:25}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="What needs attention today?"/><button className="btn" onClick={()=>{if(text){setMessages([...messages,`I checked your current farm: ${tasks[2].title} is ready, and ${tasks[3].title} needs care. I can only guide you; open the real plots to act.`]);setText("")}}}>Ask</button></div></section><aside className="panel"><div className="eyebrow">Suggested places</div><h2>Based on your farm</h2><div className="care"><Link href="/task/harvest-survey"><span>Harvest Hall feedback</span><em>Ready →</em></Link><Link href="/task/greenhouse"><span>Greenhouse spotlight</span><em>Continue →</em></Link><Link href="/campaign/orchard-house"><span>Orchard House</span><em>Visit →</em></Link></div><p className="muted">The guide can read your tasks, tally and campaigns. It cannot complete tasks, collect rewards or send requests.</p></aside></div>}

function TaskDetail({id}:{id?:string}){const task=tasks.find(t=>t.id===id)||tasks[0];const [state,setState]=useState(task.status);return <><div className="pagehead"><div><div className="eyebrow">{task.campaign} · Task plot</div><h2>{task.title}</h2><p>{task.detail}</p></div><Link href="/work" className="btn secondary">Back to work</Link></div><div className="grid2"><section className="panel"><div style={{fontSize:70}}>{task.icon}</div><span className="tag">{state}</span><h2>What this plot needs</h2><p className="muted">Follow the campaign action through the button below. Reward Farm will listen for the completion signal and update this plot automatically.</p><div className="progress"><i style={{width:`${state==="Growing"?68:task.progress}%`}}/></div><button className="btn" onClick={()=>setState("Growing")}>{state==="Ready to harvest"?"Collect harvest":"Open campaign action"}</button></section><aside className="panel"><h2>Exact plot details</h2><div className="care"><a><span>Reward</span><em>{task.reward}</em></a><a><span>Condition</span><em>{state}</em></a><a><span>Completion</span><em>Automatic</em></a><a><span>Repeat</span><em>Once</em></a></div><h3>Growth timeline</h3><p className="muted">Opened → Action detected → Growing → Ready to harvest</p></aside></div></>}

function CampaignDetail({id}:{id?:string}){const c=campaigns.find(x=>x.id===id)||campaigns[0];return <><div className="pagehead"><div><div className="eyebrow">Campaign City · Open house</div><h2>{c.icon} {c.name}</h2><p>{c.type}. Browse the real task plots currently published here.</p></div><Link href="/city" className="btn secondary">Back to city</Link></div><div className="cards">{tasks.filter((_,i)=>i<3).map(t=><TaskCard task={{...t,campaign:c.name}} key={t.id}/>)}</div></>}

function Profile({notifications=false}:{notifications?:boolean}){return <><div className="pagehead"><div><div className="eyebrow">{notifications?"Farm messages":"Profile & preferences"}</div><h2>{notifications?"Notifications":"Evans Simon"}</h2><p>{notifications?"Updates produced by real farm activity.":"Manage your invited account and farm experience."}</p></div></div>{notifications?<div className="list">{["Your Harvest Hall task is ready to collect","The owner marked your payout request as paid","Three new tasks opened in Campaign City"].map((x,i)=><div className="row" key={x}><div className="rowicon">{i===0?"🌾":i===1?"◆":"🏙️"}</div><div className="rowmain"><h3>{x}</h3><p>{i+1} hour{i?"s":""} ago</p></div></div>)}</div>:<div className="grid2"><section className="panel"><h2>Account</h2><label className="eyebrow">Display name</label><input className="search" defaultValue="Evans Simon"/><br/><br/><label className="eyebrow">Language</label><select className="filter"><option>English</option></select><br/><br/><button className="btn">Save changes</button></section><aside className="panel"><h2>Farm experience</h2><div className="care"><a><span>AI Guide</span><em>Enabled</em></a><a><span>Reduced motion</span><em>Off</em></a><a><span>Structured work view</span><em>Available</em></a><a><span>High contrast</span><em>Off</em></a></div></aside></div>}</>}

function NotFound(){return <div className="empty"><div style={{fontSize:50}}>🌱</div><h2>This path has not been planted</h2><p>Return to your Farm World and continue from a real district.</p><Link href="/" className="btn">Return to farm</Link></div>}

export function FarmApp({view,detailId}:{view:FarmView;detailId?:string}){const content=useMemo(()=>{switch(view){case"farm":return <FarmHome/>;case"work":return <Work/>;case"city":return <City/>;case"vault":return <Vault/>;case"guide":return <Guide/>;case"task":return <TaskDetail id={detailId}/>;case"campaign":return <CampaignDetail id={detailId}/>;case"profile":return <Profile/>;case"notifications":return <Profile notifications/>;default:return <NotFound/>}},[view,detailId]);return <Shell view={view}>{content}</Shell>}
