-- Reward Farm shared backend. GEM values are integer GEM CENTS.
-- The system does not move money, convert currency, or assign GEM a cash value.
create extension if not exists pgcrypto;
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, status text not null default 'active' check(status in ('active','suspended','deleted')), preferred_language text not null default 'en', timezone text, notification_preferences jsonb not null default '{"email":true,"push":true,"in_app":true}', theme text not null default 'system', ai_guide_enabled boolean not null default false, ai_guide_auto_enabled_via text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.admin_users (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id), role text not null check(role in ('admin','super_admin')), invited_by uuid references public.admin_users(id), disabled_at timestamptz, last_login_at timestamptz, created_at timestamptz not null default now());
create table public.campaigns (id uuid primary key default gen_random_uuid(), title text not null, description text, status text not null default 'draft' check(status in ('draft','published','paused','closed')), created_by uuid not null references public.admin_users(id), starts_at timestamptz, ends_at timestamptz, visual_theme text not null default 'default', accent_color text not null default '#2E7D32', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.campaigns(id), current_version int not null default 1, title text not null, instructions text not null, reward_cents bigint not null check(reward_cents>0), max_completions int, completions_count int not null default 0, status text not null default 'draft' check(status in ('draft','published','paused','closed')), repeat_type text not null default 'once' check(repeat_type in ('once','daily','cooldown')), cooldown_seconds int, max_completions_per_user int, expires_at timestamptz, locked boolean not null default false, verification_method text not null default 'webhook' check(verification_method in ('webhook','sdk_event','pixel','manual')), verification_config jsonb, verification_timeout_seconds int, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.submissions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), task_id uuid not null references public.tasks(id), task_version int not null, status text not null default 'pending' check(status in ('pending','approved','rejected','expired')), verification_path text not null check(verification_path in ('auto','manual')), match_token text unique, verification_deadline timestamptz, verified_by text, reviewed_by uuid references public.admin_users(id), rejection_reason text, created_at timestamptz not null default now(), reviewed_at timestamptz);
create table public.submission_notes (id uuid primary key default gen_random_uuid(), submission_id uuid not null unique references public.submissions(id) on delete cascade, note text, reference_link text, created_at timestamptz not null default now());
create table public.ledger_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), amount_cents bigint not null, type text not null, reference_id uuid, description text, created_at timestamptz not null default now(), unique(type,reference_id));
create table public.wallet_addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), network text, address text not null, label text, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payout_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), requested_amount_cents bigint, wallet_address_id uuid references public.wallet_addresses(id), status text not null default 'requested' check(status in ('requested','paid','dismissed')), admin_note text, created_at timestamptz not null default now(), resolved_at timestamptz);
create table public.verification_events (id uuid primary key default gen_random_uuid(), provider text not null, external_event_id text not null, match_token text, outcome text, payload jsonb not null, matched_submission_id uuid references public.submissions(id), created_at timestamptz not null default now(), unique(provider,external_event_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), title text not null, body text not null, kind text not null, delivery_channels text[] not null default array['in_app'], delivery_status jsonb not null default '{}', read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_log (id uuid primary key default gen_random_uuid(), actor_id uuid references public.admin_users(id), action text not null, target_type text not null, target_id uuid, details jsonb not null default '{}', created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.submissions enable row level security; alter table public.submission_notes enable row level security; alter table public.ledger_entries enable row level security; alter table public.wallet_addresses enable row level security; alter table public.payout_requests enable row level security; alter table public.notifications enable row level security;
create policy "profile owner read" on public.profiles for select using(auth.uid()=id);
create policy "own submissions read" on public.submissions for select using(auth.uid()=user_id);
create policy "own ledger read" on public.ledger_entries for select using(auth.uid()=user_id);
create policy "own wallet manage" on public.wallet_addresses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own requests read" on public.payout_requests for select using(auth.uid()=user_id);
create policy "own notifications read" on public.notifications for select using(auth.uid()=user_id);
